import { NextResponse } from 'next/server';

const courses = [
  {
    id: '1',
    name: 'Cabo del Sol Ocean Course',
    slug: 'cabo-del-sol-ocean-course',
    description: 'Diseñado por Jack Nicklaus, este campo ofrece vistas espectaculares al Mar de Cortés y un desafío para golfistas de todos los niveles.',
    address: 'Carretera Transpeninsular Km 10.3',
    city: 'Cabo San Lucas',
    state: 'Baja California Sur',
    phone: '+52-624-145-6300',
    website: 'https://www.cabodelsol.com/golf/ocean-course/',
    priceWeekday: 350,
    priceWeekend: 400,
    holes: 18,
    par: 72,
    length: 7075,
    image: '/images/cabo-del-sol-ocean.jpg',
    images: [
      '/images/cabo-del-sol-ocean-1.jpg',
      '/images/cabo-del-sol-ocean-2.jpg',
      '/images/cabo-del-sol-ocean-3.jpg',
    ],
    rating: 4.8,
    reviewCount: 120,
    isActive: true,
    features: 'Vista al mar, Diseño de Nicklaus, Campo de prácticas, Pro Shop, Restaurante',
    difficulty: 'Avanzado',
    teeSheetUrl: 'https://www.example.com/cabo-del-sol-tee-sheet',
    currency: 'USD',
  },
  {
    id: '2',
    name: 'Cabo Real Golf Club',
    slug: 'cabo-real-golf-club',
    description: 'Un campo de Robert Trent Jones Jr. con impresionantes vistas al océano y al desierto, conocido por sus desafiantes hoyos frente al mar.',
    address: 'Carretera Transpeninsular Km 19.5',
    city: 'San José del Cabo',
    state: 'Baja California Sur',
    phone: '+52-624-144-0040',
    website: 'https://www.caboreal.com/',
    priceWeekday: 280,
    priceWeekend: 320,
    holes: 18,
    par: 71,
    length: 6848,
    image: '/images/cabo-real.jpg',
    images: [
      '/images/cabo-real-1.jpg',
      '/images/cabo-real-2.jpg',
    ],
    rating: 4.5,
    reviewCount: 90,
    isActive: true,
    features: 'Vista al mar, Diseño de Robert Trent Jones Jr., Alquiler de equipo, Clases de golf',
    difficulty: 'Intermedio',
    teeSheetUrl: 'https://www.example.com/cabo-real-tee-sheet',
    currency: 'USD',
  },
  {
    id: '3',
    name: 'Puerto Los Cabos Golf Club',
    slug: 'puerto-los-cabos-golf-club',
    description: 'Un campo de golf único con 27 hoyos diseñados por Jack Nicklaus y Greg Norman, ofreciendo una experiencia diversa y desafiante.',
    address: 'Paseo de los Pescadores S/N',
    city: 'San José del Cabo',
    state: 'Baja California Sur',
    phone: '+52-624-144-6000',
    website: 'https://www.puertoloscabos.com/golf/',
    priceWeekday: 300,
    priceWeekend: 360,
    holes: 27,
    par: 73,
    length: 7461,
    image: '/images/puerto-los-cabos.jpg',
    images: [
      '/images/puerto-los-cabos-1.jpg',
      '/images/puerto-los-cabos-2.jpg',
    ],
    rating: 4.7,
    reviewCount: 110,
    isActive: true,
    features: 'Diseño de Nicklaus y Norman, 27 hoyos, Vistas panorámicas, Club House',
    difficulty: 'Avanzado',
    teeSheetUrl: 'https://www.example.com/puerto-los-cabos-tee-sheet',
    currency: 'USD',
  },
  {
    id: '4',
    name: 'Club Campestre San José',
    slug: 'club-campestre-san-jose',
    description: 'Un campo de 18 hoyos diseñado por Jack Nicklaus, que combina la belleza del desierto con vistas al Mar de Cortés.',
    address: 'Paseo del Malecón S/N',
    city: 'San José del Cabo',
    state: 'Baja California Sur',
    phone: '+52-624-172-6500',
    website: 'https://www.clubcampestresanjose.com/',
    priceWeekday: 250,
    priceWeekend: 290,
    holes: 18,
    par: 71,
    length: 6966,
    image: '/images/club-campestre.jpg',
    images: [
      '/images/club-campestre-1.jpg',
      '/images/club-campestre-2.jpg',
    ],
    rating: 4.4,
    reviewCount: 80,
    isActive: true,
    features: 'Diseño de Nicklaus, Campo bien mantenido, Ambiente exclusivo, Cerca de la ciudad',
    difficulty: 'Intermedio',
    teeSheetUrl: 'https://www.example.com/club-campestre-tee-sheet',
    currency: 'USD',
  },
];

export async function GET() {
  return NextResponse.json(courses);
}


